### ISSUE TITLE
Installing f2c as a local package to venv

### ISSUE THREAD

**Issue by luojinzhang** [Fields2Cover/Fields2Cover#158]
Hi, I have a repo that uses python3.10 venv, then I try to build and install F2C into venv, it's all working and running, however, I just wonder why it has this error during `pip3 install /path/to/f2c/build/swig/python/`. It would be great to know how to solve it.

```
Traceback (most recent call last):
    File "/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 38, in <module>
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 420, in run
      self.egg2dist(self.egginfo_dir, distinfo_dir)
    File "/tmp/pip-build-env-14x3_rat/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 551, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-x86_64/wheel/fields2cover-2.0.0-py3.10.egg-info but not found
  error: subprocess-exited-with-error
  
  × Building wheel for fields2cover (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /venv/bin/python3 /venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp_k7om2x2
  cwd: /fields2cover/build/swig/python
  Building wheel for fields2cover (pyproject.toml) ... error
  ERROR: Failed building wheel for fields2cover
Failed to build fields2cover
ERROR: Could not build wheels for fields2cover, which is required to install pyproject.toml-based projects
```
I did `pip3 install wheel`, add `-no-binary` as argument, `pip3 install -e /path/to/f2c/build/swig/python/` runs without error, but when I actually run it, it cannot find `fields2cover`.
Thank you.

**Comment by Gonzalo-Mier** [comment]
Can you do a step-by-step the commands you used? I'm not able to replicate this error
